spring:
 application:
  name: capstone-gateway
  
 cloud:
  gateway:
   routes:
    - id: reporting-service
      uri: http://localhost:8081
      predicates :
       - Path=/service1/**
    - id: user-service
      uri: http://localhost:5001
      predicates :
       - Path=/service2/**
    - id: calculation-service
      uri: http://localhost:8082
      predicates:
       - Path=/service3/**
   
server:
 port: 8070