spring:
 application:
  name: capstone-gateway
  
 cloud:
  gateway:
   routes:
    - id: reporting-service
      uri: http://localhost:5003
      predicates :
       - Path=/api/v1/emissions/**
    - id: user-service
      uri: http://localhost:5001
      predicates :
       - Path=/api/v1/users/**
    - id: calculation-service
      uri: http://localhost:5002
      predicates:
       - Path=/api/v1/calculate/**
   
server:
 port: 8070